# .streamlit/secrets.toml
openai_api_key = "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" 
schema_catalog_path = "schema_catalog.json"

# or inline the JSON instead of using a file:
# schema_catalog = """
# { "version":"0.1", "tables": [] }
# """
